name: Integration Tests for sv2-core-test PR

on:
  pull_request:
    branches: [main]

jobs:
  integration-tests:
    name: Run Integration Tests
    uses: GitGab19/sv2-integration-test-framework-test/.github/workflows/test-with-branch-fixed.yml@main
    with:
      repo_name: "sv2-core-test"
      branch_name: ${{ github.head_ref }}
      repo_url: ${{ github.event.pull_request.head.repo.html_url }}
      repo_slug: ${{ github.event.pull_request.head.repo.full_name }}
      pr_number: ${{ github.event.number }}
    secrets: inherit